import type { CombatSocketId, MoveDefinition } from "./types";

const defaultWindows = (startup: number, active: number, recovery: number) => ({
  startup: { start: 1, end: startup },
  active: { start: startup + 1, end: startup + active },
  recovery: {
    start: startup + active + 1,
    end: startup + active + recovery,
  },
});

export const coreMoves: Record<string, MoveDefinition> = {
  lightJab: {
    id: "lightJab",
    name: "Quick Jab",
    category: "light",
    totalFrames: 22,
    windows: defaultWindows(5, 4, 13),
    hitboxes: [
      {
        id: "jab-hit",
        frames: { start: 6, end: 9 },
        socket: "rightHand",
        radius: 0.35,
        offset: [0.8, 1.2, 0],
        height: 0.4,
        priority: 1,
        damage: 4,
        launchAngleDeg: 15,
        guard: "mid",
        hitLag: 4,
        knockback: {
          base: 6,
          scaling: 0.25,
        },
      },
    ],
    cancelBranches: [
      {
        to: "lightJab2",
        window: { start: 10, end: 16 },
        condition: "onHit",
      },
    ],
    meterGain: { stamina: 2, specialMeter: 1 },
    autoTurn: true,
  },
  lightJab2: {
    id: "lightJab2",
    name: "Hook",
    category: "light",
    totalFrames: 26,
    windows: defaultWindows(6, 5, 15),
    hitboxes: [
      {
        id: "hook-hit",
        frames: { start: 7, end: 11 },
        socket: "rightHand",
        radius: 0.45,
        offset: [0.9, 1.1, 0.1],
        height: 0.5,
        priority: 2,
        damage: 5,
        launchAngleDeg: 20,
        guard: "mid",
        hitLag: 5,
        knockback: {
          base: 8,
          scaling: 0.3,
        },
      },
    ],
    cancelBranches: [
      {
        to: "launcher",
        window: { start: 12, end: 20 },
        condition: "onHit",
      },
    ],
    meterGain: { stamina: 2, specialMeter: 1 },
  },
  launcher: {
    id: "launcher",
    name: "Rising Smash",
    category: "medium",
    totalFrames: 38,
    windows: defaultWindows(10, 6, 22),
    hitboxes: [
      {
        id: "launcher-lift",
        frames: { start: 11, end: 16 },
        socket: "rightHand",
        radius: 0.5,
        offset: [0.2, 0.6, 0],
        height: 1,
        priority: 3,
        damage: 9,
        launchAngleDeg: 75,
        guard: "mid",
        hitLag: 7,
        knockback: {
          base: 12,
          scaling: 0.6,
          gravityMultiplier: 0.8,
        },
      },
    ],
    meterCost: { stamina: 5 },
    autoTurn: true,
  },
  diveKick: {
    id: "diveKick",
    name: "Meteor Dive",
    category: "aerial",
    totalFrames: 35,
    landingLagFrames: 18,
    autoCancelWindow: { start: 1, end: 6 },
    windows: defaultWindows(4, 12, 19),
    hitboxes: [
      {
        id: "dive-hit",
        frames: { start: 5, end: 16 },
        socket: "rightFoot",
        radius: 0.55,
        offset: [0.4, 0.2, 0],
        height: 0.8,
        priority: 2,
        damage: 8,
        launchAngleDeg: -60,
        guard: "mid",
        hitLag: 8,
        knockback: {
          base: 10,
          scaling: 0.5,
          gravityMultiplier: 1.2,
        },
        causesTrip: true,
      },
    ],
    aerialOnly: true,
    meterCost: { stamina: 7 },
    meterGain: { specialMeter: 3 },
  },
  guardBreak: {
    id: "guardBreak",
    name: "Shield Crusher",
    category: "heavy",
    totalFrames: 48,
    windows: defaultWindows(16, 4, 28),
    hitboxes: [
      {
        id: "guard-break",
        frames: { start: 17, end: 20 },
        socket: "rightHand",
        radius: 0.65,
        offset: [1, 1.2, 0],
        height: 1,
        priority: 4,
        damage: 12,
        launchAngleDeg: 35,
        guard: "mid",
        hitLag: 10,
        knockback: {
          base: 14,
          scaling: 0.7,
        },
        ignoresArmor: true,
      },
    ],
    meterCost: { stamina: 10 },
    autoTurn: true,
  },
  dodge: {
    id: "dodge",
    name: "Sidestep Roll",
    category: "special",
    totalFrames: 18,
    windows: defaultWindows(2, 6, 10),
    hitboxes: [],
    invulnerableFrames: [{ start: 2, end: 9 }],
    meterCost: { stamina: 4 },
  },
  parry: {
    id: "parry",
    name: "Perfect Guard",
    category: "grab",
    totalFrames: 22,
    windows: defaultWindows(3, 5, 14),
    hitboxes: [],
    invulnerableFrames: [{ start: 3, end: 8 }],
    armorFrames: [{ start: 3, end: 9 }],
    cancelBranches: [
      {
        to: "parryCounter",
        window: { start: 4, end: 8 },
        condition: "onBlock",
      },
    ],
    meterCost: { guard: 8 },
  },
  parryCounter: {
    id: "parryCounter",
    name: "Riposte",
    category: "special",
    totalFrames: 30,
    windows: defaultWindows(6, 6, 18),
    hitboxes: [
      {
        id: "riposte-hit",
        frames: { start: 7, end: 12 },
        socket: "rightHand",
        radius: 0.6,
        offset: [0.7, 1, 0],
        height: 1,
        priority: 5,
        damage: 14,
        launchAngleDeg: 10,
        guard: "mid",
        hitLag: 9,
        knockback: {
          base: 18,
          scaling: 0.9,
        },
      },
    ],
    meterGain: { specialMeter: 5 },
  },
};

const createSwordHitbox = (
  id: string,
  frames: [number, number],
  offset: [number, number, number],
  radius = 0.55,
  height = 0.5,
  damage = 7,
  launchAngleDeg = 20,
  knockbackBase = 9,
  knockbackScaling = 0.35,
  socket: CombatSocketId = "rightHand",
) => ({
  id,
  frames: { start: frames[0], end: frames[1] },
  socket,
  radius,
  offset,
  height,
  priority: 2,
  damage,
  launchAngleDeg,
  guard: "mid" as const,
  hitLag: 6,
  knockback: {
    base: knockbackBase,
    scaling: knockbackScaling,
  },
});

const createKickHitbox = (
  id: string,
  frames: [number, number],
  offset: [number, number, number],
  radius = 0.55,
  height = 0.75,
  damage = 7,
  launchAngleDeg = 26,
  knockbackBase = 9,
  knockbackScaling = 0.35,
  socket: CombatSocketId = "rightFoot",
) => ({
  id,
  frames: { start: frames[0], end: frames[1] },
  socket,
  radius,
  offset,
  height,
  priority: 2,
  damage,
  launchAngleDeg,
  guard: "mid" as const,
  hitLag: 7,
  knockback: {
    base: knockbackBase,
    scaling: knockbackScaling,
  },
});

const createBodyHitbox = (
  id: string,
  frames: [number, number],
  offset: [number, number, number],
  radius = 0.6,
  height = 1,
  damage = 8,
  launchAngleDeg = 28,
  knockbackBase = 10,
  knockbackScaling = 0.4,
  socket: CombatSocketId = "torso",
) => ({
  id,
  frames: { start: frames[0], end: frames[1] },
  socket,
  radius,
  offset,
  height,
  priority: 3,
  damage,
  launchAngleDeg,
  guard: "mid" as const,
  hitLag: 8,
  knockback: {
    base: knockbackBase,
    scaling: knockbackScaling,
  },
});

Object.assign(coreMoves, {
  hero_jab_1: {
    id: "hero_jab_1",
    name: "Hero Jab",
    category: "light",
    totalFrames: 19,
    windows: defaultWindows(4, 3, 12),
    hitboxes: [createSwordHitbox("hero-jab", [5, 7], [0.78, 1.1, 0], 0.35, 0.4, 4, 12, 6, 0.24, "rightHand")],
    cancelBranches: [
      {
        to: "hero_tilt_side",
        window: { start: 7, end: 13 },
        condition: "onHit",
      },
    ],
    meterGain: { stamina: 2, specialMeter: 1 },
    autoTurn: true,
  },
  hero_tilt_side: {
    id: "hero_tilt_side",
    name: "Hero Tilt",
    category: "light",
    totalFrames: 25,
    windows: defaultWindows(6, 5, 14),
    hitboxes: [
      {
        ...createSwordHitbox("hero-tilt", [8, 11], [1.02, 1.16, 0.05], 0.42, 0.45, 7, 24, 9, 0.34, "rightHand"),
        hitLag: 7,
      },
    ],
    meterGain: { stamina: 3, specialMeter: 1 },
  },
  hero_sweep: {
    id: "hero_sweep",
    name: "Low Sweep",
    category: "light",
    totalFrames: 30,
    windows: defaultWindows(9, 5, 16),
    hitboxes: [
      {
        id: "hero-sweep",
        frames: { start: 10, end: 14 },
        socket: "rightFoot",
        radius: 0.65,
        offset: [0.9, 0.35, 0],
        height: 0.3,
        priority: 1,
        damage: 5,
        launchAngleDeg: 12,
        guard: "low",
        hitLag: 5,
        knockback: { base: 7, scaling: 0.25 },
        causesTrip: true,
      },
    ],
  },
  hero_launcher: {
    id: "hero_launcher",
    name: "Hero Launcher",
    category: "medium",
    totalFrames: 34,
    windows: defaultWindows(8, 5, 21),
    hitboxes: [
      {
        ...createSwordHitbox("hero-launch", [10, 13], [0.44, 0.84, 0], 0.46, 1, 9, 76, 12, 0.58, "rightHand"),
        hitLag: 8,
      },
    ],
    meterCost: { stamina: 6 },
    autoTurn: true,
  },
  hero_smash_side: {
    id: "hero_smash_side",
    name: "Hero Smash",
    category: "heavy",
    totalFrames: 52,
    windows: defaultWindows(18, 4, 30),
    hitboxes: [createSwordHitbox("hero-smash", [19, 23], [1.2, 1.3, 0], 0.75, 1, 16, 35, 16, 0.8, "rightHand")],
    meterCost: { stamina: 12 },
    autoTurn: true,
  },
  hero_air_neutral: {
    id: "hero_air_neutral",
    name: "Hero Nair",
    category: "aerial",
    totalFrames: 34,
    windows: defaultWindows(5, 10, 19),
    hitboxes: [createSwordHitbox("hero-nair", [6, 15], [0.4, 0.8, 0], 0.45, 0.8, 6, 25, 9, 0.35, "rightHand")],
    aerialOnly: true,
  },
  hero_air_forward: {
    id: "hero_air_forward",
    name: "Hero Fair",
    category: "aerial",
    totalFrames: 38,
    windows: defaultWindows(8, 5, 25),
    hitboxes: [
      {
        ...createSwordHitbox("hero-fair", [10, 14], [0.96, 0.94, 0], 0.62, 0.92, 10, 32, 12, 0.56, "rightHand"),
        hitLag: 8,
      },
    ],
    aerialOnly: true,
  },
  hero_air_down_spike: {
    id: "hero_air_down_spike",
    name: "Hero Spike",
    category: "aerial",
    totalFrames: 46,
    landingLagFrames: 20,
    windows: defaultWindows(10, 6, 30),
    hitboxes: [
      {
        id: "hero-dair",
        frames: { start: 11, end: 16 },
        socket: "rightFoot",
        radius: 0.55,
        offset: [0, 0.4, 0],
        height: 0.8,
        priority: 3,
        damage: 11,
        launchAngleDeg: -80,
        guard: "mid",
        hitLag: 9,
        knockback: { base: 13, scaling: 0.55 },
        causesTrip: true,
      },
    ],
    aerialOnly: true,
  },
  hero_neutral_proj: {
    id: "hero_neutral_proj",
    name: "Radiant Burst",
    category: "special",
    totalFrames: 32,
    windows: defaultWindows(10, 4, 18),
    hitboxes: [createSwordHitbox("hero-burst", [11, 14], [0.6, 1, 0], 0.4, 0.9, 7, 35, 9, 0.4, "rightHand")],
    meterCost: { stamina: 4, specialMeter: 3 },
  },
  hero_dash_strike: {
    id: "hero_dash_strike",
    name: "Hero Dash Strike",
    category: "special",
    totalFrames: 42,
    windows: defaultWindows(8, 6, 28),
    hitboxes: [createSwordHitbox("hero-dash", [9, 14], [1.2, 1.1, 0], 0.6, 0.9, 10, 25, 13, 0.55, "rightHand")],
    meterCost: { stamina: 8 },
    autoTurn: true,
  },
  hero_rising_recovery: {
    id: "hero_rising_recovery",
    name: "Hero Rise",
    category: "special",
    totalFrames: 48,
    windows: defaultWindows(6, 8, 34),
    hitboxes: [createSwordHitbox("hero-rise", [7, 14], [0.3, 0.6, 0], 0.45, 1.1, 7, 85, 10, 0.4, "rightHand")],
    meterCost: { stamina: 6, specialMeter: 5 },
    autoTurn: true,
  },
  hero_counter_light: {
    id: "hero_counter_light",
    name: "Hero Counter",
    category: "special",
    totalFrames: 34,
    windows: defaultWindows(4, 10, 20),
    hitboxes: [],
    invulnerableFrames: [{ start: 5, end: 12 }],
    counterGuardFrames: [{ start: 6, end: 12 }],
    cancelBranches: [
      {
        to: "hero_dash_strike",
        window: { start: 6, end: 12 },
        condition: "onBlock",
      },
    ],
  },
  vill_jab_triple: {
    id: "vill_jab_triple",
    name: "Villain Jab",
    category: "light",
    totalFrames: 24,
    windows: defaultWindows(4, 6, 14),
    hitboxes: [createSwordHitbox("vill-jab", [5, 10], [0.7, 1, 0], 0.35, 0.45, 2.5, 8, 4, 0.15, "rightHand")],
    cancelBranches: [
      { to: "vill_low_stab", window: { start: 11, end: 16 }, condition: "onHit" },
    ],
  },
  vill_guard_break_big: {
    id: "vill_guard_break_big",
    name: "Crushing Swipe",
    category: "heavy",
    totalFrames: 50,
    windows: defaultWindows(22, 4, 24),
    hitboxes: [
      {
        ...createSwordHitbox("vill-smash", [23, 26], [1.34, 1.22, 0], 0.82, 1.14, 20, 42, 20, 0.95, "rightHand"),
        hitLag: 12,
      },
    ],
    meterCost: { stamina: 11 },
    autoTurn: true,
  },
  vill_low_stab: {
    id: "vill_low_stab",
    name: "Low Stab",
    category: "light",
    totalFrames: 28,
    windows: defaultWindows(8, 6, 14),
    hitboxes: [
      {
        id: "vill-low",
        frames: { start: 9, end: 14 },
        socket: "rightHand",
        radius: 0.55,
        offset: [0.95, 0.4, 0],
        height: 0.3,
        priority: 2,
        damage: 6,
        launchAngleDeg: 10,
        guard: "low",
        hitLag: 6,
        knockback: { base: 8, scaling: 0.3 },
        causesTrip: true,
      },
    ],
  },
  vill_dive_explosion: {
    id: "vill_dive_explosion",
    name: "Toxic Dive",
    category: "aerial",
    totalFrames: 50,
    landingLagFrames: 26,
    windows: defaultWindows(12, 6, 32),
    hitboxes: [
      {
        id: "vill-dive",
        frames: { start: 13, end: 18 },
        socket: "rightFoot",
        radius: 0.6,
        offset: [0, 0.35, 0],
        height: 0.75,
        priority: 3,
        damage: 13,
        launchAngleDeg: -75,
        guard: "mid",
        hitLag: 10,
        knockback: { base: 15, scaling: 0.55 },
      },
    ],
    aerialOnly: true,
  },
  vill_poison_orb: {
    id: "vill_poison_orb",
    name: "Poison Orb",
    category: "special",
    totalFrames: 44,
    windows: defaultWindows(12, 6, 26),
    hitboxes: [createSwordHitbox("vill-orb", [13, 18], [0.5, 0.9, 0], 0.4, 1, 5, 30, 7, 0.3, "rightHand")],
    meterCost: { specialMeter: 5 },
  },
  vill_sidestep_strike: {
    id: "vill_sidestep_strike",
    name: "Sidestep Slash",
    category: "special",
    totalFrames: 38,
    windows: defaultWindows(8, 5, 25),
    hitboxes: [createSwordHitbox("vill-step", [9, 13], [0.8, 1, 0], 0.5, 0.9, 9, 30, 12, 0.5, "rightHand")],
    invulnerableFrames: [{ start: 4, end: 8 }],
    meterCost: { stamina: 7 },
  },
  vill_teleport_recover: {
    id: "vill_teleport_recover",
    name: "Shadow Rise",
    category: "special",
    totalFrames: 46,
    windows: defaultWindows(6, 6, 34),
    hitboxes: [createSwordHitbox("vill-tele", [7, 12], [0.2, 0.6, 0], 0.4, 1, 6, 80, 9, 0.35, "rightHand")],
    invulnerableFrames: [{ start: 1, end: 6 }],
    meterCost: { specialMeter: 6 },
  },
  vill_trap: {
    id: "vill_trap",
    name: "Shadow Trap",
    category: "special",
    totalFrames: 50,
    windows: defaultWindows(14, 6, 30),
    hitboxes: [createSwordHitbox("vill-trap", [15, 20], [0.4, 0.3, 0], 0.5, 0.4, 4, 15, 5, 0.2, "rightHand")],
    meterCost: { stamina: 4, specialMeter: 3 },
  },
  kite_feather_jab: {
    id: "kite_feather_jab",
    name: "Feather Jab",
    category: "light",
    totalFrames: 18,
    windows: defaultWindows(4, 3, 11),
    hitboxes: [
      {
        ...createSwordHitbox("kite-jab", [5, 7], [0.66, 1.08, 0], 0.32, 0.38, 3.5, 16, 5, 0.18, "rightHand"),
        hitLag: 5,
      },
    ],
    cancelBranches: [
      {
        to: "kite_wing_slice",
        window: { start: 7, end: 12 },
        condition: "onHit",
      },
    ],
    meterGain: { stamina: 2, specialMeter: 1 },
    autoTurn: true,
  },
  kite_wing_slice: {
    id: "kite_wing_slice",
    name: "Wing Slice",
    category: "light",
    totalFrames: 24,
    windows: defaultWindows(6, 4, 14),
    hitboxes: [
      {
        ...createKickHitbox("kite-wing", [7, 10], [0.92, 0.92, 0], 0.48, 0.82, 6.5, 22, 8, 0.32, "rightFoot"),
        hitLag: 7,
      },
    ],
    meterGain: { stamina: 3, specialMeter: 1 },
    autoTurn: true,
  },
  kite_slide_kick: {
    id: "kite_slide_kick",
    name: "Slide Kick",
    category: "light",
    totalFrames: 28,
    windows: defaultWindows(7, 5, 16),
    hitboxes: [
      {
        id: "kite-slide",
        frames: { start: 8, end: 12 },
        socket: "rightFoot",
        radius: 0.62,
        offset: [0.92, 0.24, 0],
        height: 0.24,
        priority: 1,
        damage: 5,
        launchAngleDeg: 8,
        guard: "low",
        hitLag: 6,
        knockback: { base: 7, scaling: 0.24 },
        causesTrip: true,
      },
    ],
  },
  kite_sky_hook: {
    id: "kite_sky_hook",
    name: "Sky Hook",
    category: "medium",
    totalFrames: 32,
    windows: defaultWindows(7, 5, 20),
    hitboxes: [
      {
        ...createKickHitbox("kite-hook", [8, 12], [0.24, 0.78, 0], 0.5, 1.08, 8, 82, 11, 0.56, "rightFoot"),
        hitLag: 8,
        knockback: { base: 11, scaling: 0.56, gravityMultiplier: 0.76 },
      },
    ],
    meterCost: { stamina: 5 },
    autoTurn: true,
  },
  kite_tail_whip: {
    id: "kite_tail_whip",
    name: "Tail Whip",
    category: "heavy",
    totalFrames: 46,
    windows: defaultWindows(15, 5, 26),
    hitboxes: [
      {
        ...createKickHitbox("kite-whip", [16, 20], [1.18, 0.88, 0], 0.74, 1, 14, 30, 14, 0.74, "rightFoot"),
        hitLag: 10,
      },
    ],
    meterCost: { stamina: 10 },
    autoTurn: true,
  },
  kite_air_swirl: {
    id: "kite_air_swirl",
    name: "Air Swirl",
    category: "aerial",
    totalFrames: 30,
    windows: defaultWindows(5, 8, 17),
    hitboxes: [
      {
        id: "kite-swirl",
        frames: { start: 6, end: 13 },
        socket: "torso",
        radius: 0.56,
        offset: [0.22, 0.82, 0],
        height: 0.92,
        priority: 2,
        damage: 6,
        launchAngleDeg: 34,
        guard: "mid",
        hitLag: 7,
        knockback: { base: 9, scaling: 0.36 },
      },
    ],
    aerialOnly: true,
    meterGain: { specialMeter: 2 },
  },
  kite_air_flick: {
    id: "kite_air_flick",
    name: "Air Flick",
    category: "aerial",
    totalFrames: 34,
    windows: defaultWindows(7, 5, 22),
    hitboxes: [
      {
        ...createKickHitbox("kite-flick", [8, 12], [1.02, 0.86, 0], 0.58, 0.9, 9, 28, 11, 0.48, "rightFoot"),
        hitLag: 8,
      },
    ],
    aerialOnly: true,
  },
  kite_dive_screw: {
    id: "kite_dive_screw",
    name: "Dive Screw",
    category: "aerial",
    totalFrames: 42,
    landingLagFrames: 18,
    windows: defaultWindows(8, 7, 27),
    hitboxes: [
      {
        id: "kite-screw",
        frames: { start: 9, end: 15 },
        socket: "rightFoot",
        radius: 0.54,
        offset: [0.08, 0.28, 0],
        height: 0.82,
        priority: 3,
        damage: 10,
        launchAngleDeg: -76,
        guard: "mid",
        hitLag: 9,
        knockback: { base: 12, scaling: 0.52, gravityMultiplier: 1.16 },
        causesTrip: true,
      },
    ],
    aerialOnly: true,
  },
  kite_gale_pulse: {
    id: "kite_gale_pulse",
    name: "Gale Pulse",
    category: "special",
    totalFrames: 34,
    windows: defaultWindows(8, 6, 20),
    hitboxes: [
      {
        id: "kite-gale",
        frames: { start: 9, end: 14 },
        socket: "torso",
        radius: 0.62,
        offset: [0.46, 0.92, 0],
        height: 0.96,
        priority: 3,
        damage: 6,
        launchAngleDeg: 40,
        guard: "mid",
        hitLag: 7,
        knockback: { base: 9, scaling: 0.34 },
      },
    ],
    meterCost: { stamina: 4, specialMeter: 2 },
  },
  kite_drift_break: {
    id: "kite_drift_break",
    name: "Drift Break",
    category: "special",
    totalFrames: 36,
    windows: defaultWindows(6, 6, 24),
    hitboxes: [
      {
        ...createKickHitbox("kite-drift", [7, 12], [0.92, 0.94, 0], 0.58, 0.9, 8, 26, 10, 0.42, "rightFoot"),
        hitLag: 8,
      },
    ],
    invulnerableFrames: [{ start: 3, end: 8 }],
    meterCost: { stamina: 6 },
    autoTurn: true,
  },
  kite_updraft_rise: {
    id: "kite_updraft_rise",
    name: "Updraft Rise",
    category: "special",
    totalFrames: 42,
    windows: defaultWindows(5, 8, 29),
    hitboxes: [
      {
        id: "kite-rise",
        frames: { start: 6, end: 13 },
        socket: "torso",
        radius: 0.46,
        offset: [0.2, 0.72, 0],
        height: 1.16,
        priority: 3,
        damage: 7,
        launchAngleDeg: 84,
        guard: "mid",
        hitLag: 7,
        knockback: { base: 10, scaling: 0.34, gravityMultiplier: 0.72 },
      },
    ],
    invulnerableFrames: [{ start: 1, end: 5 }],
    meterCost: { stamina: 5, specialMeter: 4 },
    autoTurn: true,
  },
  kite_crosswind_feint: {
    id: "kite_crosswind_feint",
    name: "Crosswind Feint",
    category: "special",
    totalFrames: 32,
    windows: defaultWindows(5, 5, 22),
    hitboxes: [
      {
        ...createKickHitbox("kite-feint", [6, 10], [0.72, 0.82, 0], 0.44, 0.72, 5, 20, 7, 0.24, "leftFoot"),
        hitLag: 6,
      },
    ],
    invulnerableFrames: [{ start: 3, end: 7 }],
    meterCost: { stamina: 4 },
  },
  anvil_club_jab: {
    id: "anvil_club_jab",
    name: "Club Jab",
    category: "light",
    totalFrames: 22,
    windows: defaultWindows(5, 4, 13),
    hitboxes: [
      {
        ...createBodyHitbox("anvil-jab", [6, 9], [0.72, 1.02, 0], 0.42, 0.58, 5, 14, 7, 0.22, "rightHand"),
        hitLag: 6,
      },
    ],
    cancelBranches: [
      {
        to: "anvil_shoulder_check",
        window: { start: 9, end: 15 },
        condition: "onHit",
      },
    ],
    meterGain: { stamina: 2, specialMeter: 1 },
    autoTurn: true,
  },
  anvil_shoulder_check: {
    id: "anvil_shoulder_check",
    name: "Shoulder Check",
    category: "light",
    totalFrames: 28,
    windows: defaultWindows(7, 5, 16),
    hitboxes: [
      {
        ...createBodyHitbox("anvil-shoulder", [8, 12], [0.82, 0.94, 0], 0.64, 0.96, 7, 20, 9, 0.34, "torso"),
        hitLag: 8,
      },
    ],
    armorFrames: [{ start: 6, end: 11 }],
    meterGain: { stamina: 3, specialMeter: 1 },
    autoTurn: true,
  },
  anvil_headbutt_lift: {
    id: "anvil_headbutt_lift",
    name: "Headbutt Lift",
    category: "medium",
    totalFrames: 34,
    windows: defaultWindows(8, 5, 21),
    hitboxes: [
      {
        ...createBodyHitbox("anvil-headbutt", [9, 13], [0.28, 1.16, 0], 0.52, 1.04, 9, 78, 12, 0.6, "head"),
        hitLag: 9,
        knockback: { base: 12, scaling: 0.6, gravityMultiplier: 0.8 },
      },
    ],
    meterCost: { stamina: 6 },
    autoTurn: true,
  },
  anvil_ankle_stamp: {
    id: "anvil_ankle_stamp",
    name: "Ankle Stamp",
    category: "light",
    totalFrames: 30,
    windows: defaultWindows(8, 5, 17),
    hitboxes: [
      {
        id: "anvil-stamp",
        frames: { start: 9, end: 13 },
        socket: "rightFoot",
        radius: 0.68,
        offset: [0.94, 0.24, 0],
        height: 0.26,
        priority: 1,
        damage: 6,
        launchAngleDeg: 10,
        guard: "low",
        hitLag: 7,
        knockback: { base: 8, scaling: 0.28 },
        causesTrip: true,
      },
    ],
  },
  anvil_hammer_fall: {
    id: "anvil_hammer_fall",
    name: "Hammer Fall",
    category: "heavy",
    totalFrames: 52,
    windows: defaultWindows(18, 5, 29),
    hitboxes: [
      {
        ...createBodyHitbox("anvil-fall", [19, 23], [1.04, 1.12, 0], 0.82, 1.14, 18, 34, 18, 0.88, "rightHand"),
        hitLag: 12,
        ignoresArmor: true,
      },
    ],
    armorFrames: [{ start: 12, end: 18 }],
    meterCost: { stamina: 12 },
    autoTurn: true,
  },
  anvil_body_press: {
    id: "anvil_body_press",
    name: "Body Press",
    category: "aerial",
    totalFrames: 34,
    windows: defaultWindows(5, 10, 19),
    hitboxes: [
      {
        ...createBodyHitbox("anvil-press", [6, 15], [0.32, 0.84, 0], 0.7, 1.02, 8, 26, 10, 0.4, "torso"),
        hitLag: 8,
      },
    ],
    aerialOnly: true,
  },
  anvil_air_lariat: {
    id: "anvil_air_lariat",
    name: "Air Lariat",
    category: "aerial",
    totalFrames: 38,
    windows: defaultWindows(8, 6, 24),
    hitboxes: [
      {
        ...createBodyHitbox("anvil-lariat", [9, 14], [0.88, 0.96, 0], 0.68, 0.96, 11, 30, 13, 0.54, "rightHand"),
        hitLag: 9,
      },
    ],
    aerialOnly: true,
  },
  anvil_elbow_drop: {
    id: "anvil_elbow_drop",
    name: "Elbow Drop",
    category: "aerial",
    totalFrames: 44,
    landingLagFrames: 22,
    windows: defaultWindows(9, 7, 28),
    hitboxes: [
      {
        ...createBodyHitbox("anvil-drop", [10, 16], [0.18, 0.42, 0], 0.58, 0.86, 12, -78, 14, 0.58, "rightHand"),
        hitLag: 10,
        knockback: { base: 14, scaling: 0.58, gravityMultiplier: 1.2 },
        causesTrip: true,
      },
    ],
    aerialOnly: true,
  },
  anvil_iron_bellow: {
    id: "anvil_iron_bellow",
    name: "Iron Bellow",
    category: "special",
    totalFrames: 36,
    windows: defaultWindows(9, 6, 21),
    hitboxes: [
      {
        ...createBodyHitbox("anvil-bellow", [10, 15], [0.48, 0.94, 0], 0.76, 1.04, 7, 38, 9, 0.32, "torso"),
        hitLag: 8,
      },
    ],
    meterCost: { stamina: 4, specialMeter: 2 },
  },
  anvil_bulldoze: {
    id: "anvil_bulldoze",
    name: "Bulldoze",
    category: "special",
    totalFrames: 40,
    windows: defaultWindows(6, 8, 26),
    hitboxes: [
      {
        ...createBodyHitbox("anvil-bulldoze", [7, 14], [0.96, 0.9, 0], 0.78, 1.02, 10, 22, 13, 0.5, "torso"),
        hitLag: 9,
      },
    ],
    armorFrames: [{ start: 5, end: 12 }],
    meterCost: { stamina: 8 },
    autoTurn: true,
  },
  anvil_brace_counter: {
    id: "anvil_brace_counter",
    name: "Brace Counter",
    category: "special",
    totalFrames: 34,
    windows: defaultWindows(4, 8, 22),
    hitboxes: [],
    armorFrames: [{ start: 4, end: 11 }],
    invulnerableFrames: [{ start: 4, end: 7 }],
    counterGuardFrames: [{ start: 5, end: 11 }],
    cancelBranches: [
      {
        to: "anvil_hammer_fall",
        window: { start: 6, end: 11 },
        condition: "onBlock",
      },
    ],
    meterCost: { guard: 10 },
  },
  anvil_rising_crash: {
    id: "anvil_rising_crash",
    name: "Rising Crash",
    category: "special",
    totalFrames: 46,
    windows: defaultWindows(6, 8, 32),
    hitboxes: [
      {
        ...createBodyHitbox("anvil-rise", [7, 14], [0.24, 0.76, 0], 0.6, 1.18, 8, 84, 11, 0.38, "torso"),
        hitLag: 8,
        knockback: { base: 11, scaling: 0.38, gravityMultiplier: 0.74 },
      },
    ],
    invulnerableFrames: [{ start: 1, end: 5 }],
    meterCost: { stamina: 6, specialMeter: 4 },
    autoTurn: true,
  },
  anvil_quake_slam: {
    id: "anvil_quake_slam",
    name: "Quake Slam",
    category: "special",
    totalFrames: 44,
    windows: defaultWindows(12, 6, 26),
    hitboxes: [
      {
        id: "anvil-quake",
        frames: { start: 13, end: 18 },
        socket: "torso",
        radius: 0.82,
        offset: [0.52, 0.34, 0],
        height: 0.42,
        priority: 3,
        damage: 9,
        launchAngleDeg: 18,
        guard: "low",
        hitLag: 9,
        knockback: { base: 11, scaling: 0.34 },
        causesTrip: true,
      },
    ],
    armorFrames: [{ start: 10, end: 15 }],
    meterCost: { stamina: 7, specialMeter: 2 },
  },
});

export type MoveSet = typeof coreMoves;
