import type { MoveDefinition } from "./types";

const defaultWindows = (startup: number, active: number, recovery: number) => ({
  startup: { start: 1, end: startup },
  active: { start: startup + 1, end: startup + active },
  recovery: {
    start: startup + active + 1,
    end: startup + active + recovery,
  },
});

export const coreMoves: Record<string, MoveDefinition> = {
  lightJab: {
    id: "lightJab",
    name: "Quick Jab",
    category: "light",
    totalFrames: 22,
    windows: defaultWindows(5, 4, 13),
    hitboxes: [
      {
        id: "jab-hit",
        frames: { start: 6, end: 9 },
        radius: 0.35,
        offset: [0.8, 1.2, 0],
        height: 0.4,
        priority: 1,
        damage: 4,
        launchAngleDeg: 15,
        guard: "mid",
        hitLag: 4,
        knockback: {
          base: 6,
          scaling: 0.25,
        },
      },
    ],
    cancelBranches: [
      {
        to: "lightJab2",
        window: { start: 10, end: 16 },
        condition: "onHit",
      },
    ],
    meterGain: { stamina: 2, specialMeter: 1 },
    autoTurn: true,
  },
  lightJab2: {
    id: "lightJab2",
    name: "Hook",
    category: "light",
    totalFrames: 26,
    windows: defaultWindows(6, 5, 15),
    hitboxes: [
      {
        id: "hook-hit",
        frames: { start: 7, end: 11 },
        radius: 0.45,
        offset: [0.9, 1.1, 0.1],
        height: 0.5,
        priority: 2,
        damage: 5,
        launchAngleDeg: 20,
        guard: "mid",
        hitLag: 5,
        knockback: {
          base: 8,
          scaling: 0.3,
        },
      },
    ],
    cancelBranches: [
      {
        to: "launcher",
        window: { start: 12, end: 20 },
        condition: "onHit",
      },
    ],
    meterGain: { stamina: 2, specialMeter: 1 },
  },
  launcher: {
    id: "launcher",
    name: "Rising Smash",
    category: "medium",
    totalFrames: 38,
    windows: defaultWindows(10, 6, 22),
    hitboxes: [
      {
        id: "launcher-lift",
        frames: { start: 11, end: 16 },
        radius: 0.5,
        offset: [0.2, 0.6, 0],
        height: 1,
        priority: 3,
        damage: 9,
        launchAngleDeg: 75,
        guard: "mid",
        hitLag: 7,
        knockback: {
          base: 12,
          scaling: 0.6,
          gravityMultiplier: 0.8,
        },
      },
    ],
    meterCost: { stamina: 5 },
    autoTurn: true,
  },
  diveKick: {
    id: "diveKick",
    name: "Meteor Dive",
    category: "aerial",
    totalFrames: 35,
    landingLagFrames: 18,
    autoCancelWindow: { start: 1, end: 6 },
    windows: defaultWindows(4, 12, 19),
    hitboxes: [
      {
        id: "dive-hit",
        frames: { start: 5, end: 16 },
        radius: 0.55,
        offset: [0.4, 0.2, 0],
        height: 0.8,
        priority: 2,
        damage: 8,
        launchAngleDeg: -60,
        guard: "mid",
        hitLag: 8,
        knockback: {
          base: 10,
          scaling: 0.5,
          gravityMultiplier: 1.2,
        },
        causesTrip: true,
      },
    ],
    aerialOnly: true,
    meterCost: { stamina: 7 },
    meterGain: { specialMeter: 3 },
  },
  guardBreak: {
    id: "guardBreak",
    name: "Shield Crusher",
    category: "heavy",
    totalFrames: 48,
    windows: defaultWindows(16, 4, 28),
    hitboxes: [
      {
        id: "guard-break",
        frames: { start: 17, end: 20 },
        radius: 0.65,
        offset: [1, 1.2, 0],
        height: 1,
        priority: 4,
        damage: 12,
        launchAngleDeg: 35,
        guard: "mid",
        hitLag: 10,
        knockback: {
          base: 14,
          scaling: 0.7,
        },
        ignoresArmor: true,
      },
    ],
    meterCost: { stamina: 10 },
    autoTurn: true,
  },
  parry: {
    id: "parry",
    name: "Perfect Guard",
    category: "grab",
    totalFrames: 24,
    windows: defaultWindows(3, 6, 15),
    hitboxes: [],
    invulnerableFrames: [{ start: 3, end: 8 }],
    armorFrames: [{ start: 3, end: 10 }],
    cancelBranches: [
      {
        to: "parryCounter",
        window: { start: 4, end: 8 },
        condition: "onBlock",
      },
    ],
    meterCost: { guard: 8 },
  },
  parryCounter: {
    id: "parryCounter",
    name: "Riposte",
    category: "special",
    totalFrames: 30,
    windows: defaultWindows(6, 6, 18),
    hitboxes: [
      {
        id: "riposte-hit",
        frames: { start: 7, end: 12 },
        radius: 0.6,
        offset: [0.7, 1, 0],
        height: 1,
        priority: 5,
        damage: 14,
        launchAngleDeg: 10,
        guard: "mid",
        hitLag: 9,
        knockback: {
          base: 18,
          scaling: 0.9,
        },
      },
    ],
    meterGain: { specialMeter: 5 },
  },
};

const createSwordHitbox = (
  id: string,
  frames: [number, number],
  offset: [number, number, number],
  radius = 0.55,
  height = 0.5,
  damage = 7,
  launchAngleDeg = 20,
  knockbackBase = 9,
  knockbackScaling = 0.35,
) => ({
  id,
  frames: { start: frames[0], end: frames[1] },
  radius,
  offset,
  height,
  priority: 2,
  damage,
  launchAngleDeg,
  guard: "mid" as const,
  hitLag: 6,
  knockback: {
    base: knockbackBase,
    scaling: knockbackScaling,
  },
});

Object.assign(coreMoves, {
  hero_jab_1: {
    id: "hero_jab_1",
    name: "Hero Jab",
    category: "light",
    totalFrames: 20,
    windows: defaultWindows(4, 4, 12),
    hitboxes: [createSwordHitbox("hero-jab", [5, 8], [0.75, 1.1, 0], 0.35, 0.4, 3, 10, 5, 0.2)],
    cancelBranches: [
      {
        to: "hero_tilt_side",
        window: { start: 8, end: 14 },
        condition: "onHit",
      },
    ],
    meterGain: { stamina: 2, specialMeter: 1 },
    autoTurn: true,
  },
  hero_tilt_side: {
    id: "hero_tilt_side",
    name: "Hero Tilt",
    category: "light",
    totalFrames: 26,
    windows: defaultWindows(7, 5, 14),
    hitboxes: [createSwordHitbox("hero-tilt", [8, 12], [1, 1.15, 0.05], 0.4, 0.45, 6, 20, 8, 0.3)],
    meterGain: { stamina: 3, specialMeter: 1 },
  },
  hero_sweep: {
    id: "hero_sweep",
    name: "Low Sweep",
    category: "light",
    totalFrames: 30,
    windows: defaultWindows(9, 5, 16),
    hitboxes: [
      {
        id: "hero-sweep",
        frames: { start: 10, end: 14 },
        radius: 0.65,
        offset: [0.9, 0.35, 0],
        height: 0.3,
        priority: 1,
        damage: 5,
        launchAngleDeg: 12,
        guard: "low",
        hitLag: 5,
        knockback: { base: 7, scaling: 0.25 },
        causesTrip: true,
      },
    ],
  },
  hero_launcher: {
    id: "hero_launcher",
    name: "Hero Launcher",
    category: "medium",
    totalFrames: 36,
    windows: defaultWindows(9, 5, 22),
    hitboxes: [createSwordHitbox("hero-launch", [10, 14], [0.4, 0.8, 0], 0.45, 1, 8, 70, 11, 0.5)],
    meterCost: { stamina: 6 },
    autoTurn: true,
  },
  hero_smash_side: {
    id: "hero_smash_side",
    name: "Hero Smash",
    category: "heavy",
    totalFrames: 52,
    windows: defaultWindows(18, 4, 30),
    hitboxes: [createSwordHitbox("hero-smash", [19, 23], [1.2, 1.3, 0], 0.75, 1, 16, 35, 16, 0.8)],
    meterCost: { stamina: 12 },
    autoTurn: true,
  },
  hero_air_neutral: {
    id: "hero_air_neutral",
    name: "Hero Nair",
    category: "aerial",
    totalFrames: 34,
    windows: defaultWindows(5, 10, 19),
    hitboxes: [createSwordHitbox("hero-nair", [6, 15], [0.4, 0.8, 0], 0.45, 0.8, 6, 25, 9, 0.35)],
    aerialOnly: true,
  },
  hero_air_forward: {
    id: "hero_air_forward",
    name: "Hero Fair",
    category: "aerial",
    totalFrames: 40,
    windows: defaultWindows(7, 7, 26),
    hitboxes: [createSwordHitbox("hero-fair", [9, 15], [0.9, 0.9, 0], 0.6, 0.9, 9, 30, 11, 0.5)],
    aerialOnly: true,
  },
  hero_air_down_spike: {
    id: "hero_air_down_spike",
    name: "Hero Spike",
    category: "aerial",
    totalFrames: 46,
    landingLagFrames: 20,
    windows: defaultWindows(10, 6, 30),
    hitboxes: [
      {
        id: "hero-dair",
        frames: { start: 11, end: 16 },
        radius: 0.55,
        offset: [0, 0.4, 0],
        height: 0.8,
        priority: 3,
        damage: 11,
        launchAngleDeg: -80,
        guard: "mid",
        hitLag: 9,
        knockback: { base: 13, scaling: 0.55 },
        causesTrip: true,
      },
    ],
    aerialOnly: true,
  },
  hero_neutral_proj: {
    id: "hero_neutral_proj",
    name: "Radiant Burst",
    category: "special",
    totalFrames: 32,
    windows: defaultWindows(10, 4, 18),
    hitboxes: [createSwordHitbox("hero-burst", [11, 14], [0.6, 1, 0], 0.4, 0.9, 7, 35, 9, 0.4)],
    meterCost: { stamina: 4, specialMeter: 3 },
  },
  hero_dash_strike: {
    id: "hero_dash_strike",
    name: "Hero Dash Strike",
    category: "special",
    totalFrames: 42,
    windows: defaultWindows(8, 6, 28),
    hitboxes: [createSwordHitbox("hero-dash", [9, 14], [1.2, 1.1, 0], 0.6, 0.9, 10, 25, 13, 0.55)],
    meterCost: { stamina: 8 },
    autoTurn: true,
  },
  hero_rising_recovery: {
    id: "hero_rising_recovery",
    name: "Hero Rise",
    category: "special",
    totalFrames: 48,
    windows: defaultWindows(6, 8, 34),
    hitboxes: [createSwordHitbox("hero-rise", [7, 14], [0.3, 0.6, 0], 0.45, 1.1, 7, 85, 10, 0.4)],
    meterCost: { stamina: 6, specialMeter: 5 },
    autoTurn: true,
  },
  hero_counter_light: {
    id: "hero_counter_light",
    name: "Hero Counter",
    category: "special",
    totalFrames: 34,
    windows: defaultWindows(4, 10, 20),
    hitboxes: [],
    invulnerableFrames: [{ start: 5, end: 12 }],
    cancelBranches: [
      {
        to: "hero_dash_strike",
        window: { start: 6, end: 12 },
        condition: "onBlock",
      },
    ],
  },
  vill_jab_triple: {
    id: "vill_jab_triple",
    name: "Villain Jab",
    category: "light",
    totalFrames: 24,
    windows: defaultWindows(4, 6, 14),
    hitboxes: [createSwordHitbox("vill-jab", [5, 10], [0.7, 1, 0], 0.35, 0.45, 2.5, 8, 4, 0.15)],
    cancelBranches: [
      { to: "vill_low_stab", window: { start: 11, end: 16 }, condition: "onHit" },
    ],
  },
  vill_guard_break_big: {
    id: "vill_guard_break_big",
    name: "Crushing Swipe",
    category: "heavy",
    totalFrames: 56,
    windows: defaultWindows(20, 4, 32),
    hitboxes: [createSwordHitbox("vill-smash", [21, 24], [1.3, 1.2, 0], 0.8, 1.1, 18, 40, 18, 0.9)],
    meterCost: { stamina: 11 },
    autoTurn: true,
  },
  vill_low_stab: {
    id: "vill_low_stab",
    name: "Low Stab",
    category: "light",
    totalFrames: 28,
    windows: defaultWindows(8, 6, 14),
    hitboxes: [
      {
        id: "vill-low",
        frames: { start: 9, end: 14 },
        radius: 0.55,
        offset: [0.95, 0.4, 0],
        height: 0.3,
        priority: 2,
        damage: 6,
        launchAngleDeg: 10,
        guard: "low",
        hitLag: 6,
        knockback: { base: 8, scaling: 0.3 },
        causesTrip: true,
      },
    ],
  },
  vill_dive_explosion: {
    id: "vill_dive_explosion",
    name: "Toxic Dive",
    category: "aerial",
    totalFrames: 50,
    landingLagFrames: 26,
    windows: defaultWindows(12, 6, 32),
    hitboxes: [
      {
        id: "vill-dive",
        frames: { start: 13, end: 18 },
        radius: 0.6,
        offset: [0, 0.35, 0],
        height: 0.75,
        priority: 3,
        damage: 13,
        launchAngleDeg: -75,
        guard: "mid",
        hitLag: 10,
        knockback: { base: 15, scaling: 0.55 },
      },
    ],
    aerialOnly: true,
  },
  vill_poison_orb: {
    id: "vill_poison_orb",
    name: "Poison Orb",
    category: "special",
    totalFrames: 44,
    windows: defaultWindows(12, 6, 26),
    hitboxes: [createSwordHitbox("vill-orb", [13, 18], [0.5, 0.9, 0], 0.4, 1, 5, 30, 7, 0.3)],
    meterCost: { specialMeter: 5 },
  },
  vill_sidestep_strike: {
    id: "vill_sidestep_strike",
    name: "Sidestep Slash",
    category: "special",
    totalFrames: 38,
    windows: defaultWindows(8, 5, 25),
    hitboxes: [createSwordHitbox("vill-step", [9, 13], [0.8, 1, 0], 0.5, 0.9, 9, 30, 12, 0.5)],
    invulnerableFrames: [{ start: 4, end: 8 }],
    meterCost: { stamina: 7 },
  },
  vill_teleport_recover: {
    id: "vill_teleport_recover",
    name: "Shadow Rise",
    category: "special",
    totalFrames: 46,
    windows: defaultWindows(6, 6, 34),
    hitboxes: [createSwordHitbox("vill-tele", [7, 12], [0.2, 0.6, 0], 0.4, 1, 6, 80, 9, 0.35)],
    invulnerableFrames: [{ start: 1, end: 6 }],
    meterCost: { specialMeter: 6 },
  },
  vill_trap: {
    id: "vill_trap",
    name: "Shadow Trap",
    category: "special",
    totalFrames: 50,
    windows: defaultWindows(14, 6, 30),
    hitboxes: [createSwordHitbox("vill-trap", [15, 20], [0.4, 0.3, 0], 0.5, 0.4, 4, 15, 5, 0.2)],
    meterCost: { stamina: 4, specialMeter: 3 },
  },
});

export type MoveSet = typeof coreMoves;
